name: Integrations tests (Docker)
on: push

jobs:
  docker-image-test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - uses: actions/checkout@v3
      - name: Build images
        run: docker compose build
      - name: Redis Test
        run: docker compose run test-redis
      - name: TCP Test
        run: docker compose run test-tcp
      - name: PostgreSQL Test
        run: docker compose run test-postgres
      - name: Http Test
        run: docker compose run test-http
      - name: MongoDB Test
        run: docker compose run test-mongodb
