name: Integrations tests (App)
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
     - uses: actions/setup-go@v3
       with:
         go-version: '1.19'
         check-latest: true
         cache: true
     - run: GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -o wait4it
     - name: Cache wait4it
       uses: actions/cache@v3
       with:
         path: wait4it
         key: wait4it-${{ github.run_id }}
         restore-keys: wait4it-${{ github.run_id }}

  redis-tcp:
    runs-on: ubuntu-latest
    needs: build
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - name: Retrieve wait4it
        uses: actions/cache@v3
        with:
          path: wait4it
          key: wait4it-${{ github.run_id }}
      - name: Test Redis
        run: ./wait4it -type=redis -p=6379 -t=60 -h=127.0.0.1
      - name: Test TCP
        run: ./wait4it -type=tcp -h=127.0.0.1 -p=6379 -t=60

  postgres:
    runs-on: ubuntu-latest
    needs: build
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
    steps:
      - name: Retrieve wait4it
        uses: actions/cache@v3
        with:
          path: wait4it
          key: wait4it-${{ github.run_id }}
      - name: Test Postgres
        run: ./wait4it -type=postgres -h=127.0.0.1 -p=5432 -t=60 -u=postgres -P=postgres -ssl=disable

  mysql:
    runs-on: ubuntu-latest
    needs: build
    services:
      redis:
        image: mysql
        env:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: app
        ports:
          - 3306:3306
    steps:
      - name: Retrieve wait4it
        uses: actions/cache@v3
        with:
          path: wait4it
          key: wait4it-${{ github.run_id }}
      - name: Test Postgres
        run: ./wait4it -type=mysql -h=127.0.0.1 -p=3306 -t=60 -u=root -P=secret -n=app

  http:
    runs-on: ubuntu-latest
    needs: build
    services:
      redis:
        image: nginx
        ports:
          - 80:80
    steps:
      - name: Retrieve wait4it
        uses: actions/cache@v3
        with:
          path: wait4it
          key: wait4it-${{ github.run_id }}
      - name: Test HTTP
        run: ./wait4it -type=http -h=http://127.0.0.1/ -t=60 -status-code=200 -http-text="Welcome to nginx!"
