name: Integrations tests (Docker)
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and cache
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          tags: "ph4r5h4d/wait4it:${{ github.run_id }}"
          cache-from: type=gha
          cache-to: type=gha,mode=max

  redis-tcp:
    runs-on: ubuntu-latest
    needs: build
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and cache
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          load: true
          tags: "ph4r5h4d/wait4it:${{ github.run_id }}"
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - uses: actions/checkout@v3
      - name: Test Redis
        run: docker run ph4r5h4d/wait4it:${{ github.run_id }} -type=redis -p=6379 -t=60 -h=127.0.0.1
      - name: Test TCP
        run: docker run ph4r5h4d/wait4it:${{ github.run_id }} -type=tcp -h=127.0.0.1 -p=6379 -t=60

