name: Integrations tests (Docker)
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

#      - name: Build and cache
#        uses: docker/build-push-action@v3
#        with:
#          context: .
#          push: false
#          tags: "ph4r5h4d/wait4it:${{ github.run_id }}"
#          outputs: type=docker,dest=docker-image.tar
#
#      - name: Cache wait4it docker image
#        uses: actions/cache@v3
#        with:
#          path: docker-image.tar
#          key: wait4it-docker-${{ github.run_id }}
#          restore-keys: wait4it-docker-${{ github.run_id }}

  redis-tcp:
    runs-on: ubuntu-latest
    needs: build
    services:
      redis:
        image: redis

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Retrieve wait4it docker image
        uses: actions/cache@v3
        with:
          path: docker-image.tar
          key: wait4it-docker-${{ github.run_id }}

      - name: Load Docker image
        run: |
          docker load --input docker-image.tar
          docker image ls -a
          docker network ls
          docker ps -a

      - name: Test Redis
        run: docker run ph4r5h4d/wait4it:${{ github.run_id }} -type=redis -p=6379 -t=60 -h=redis
      - name: Test TCP
        run: docker run ph4r5h4d/wait4it:${{ github.run_id }} -type=tcp -h=redis -p=6379 -t=60

