name: Integrations tests
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
     - uses: actions/setup-go@v3
       with:
         go-version: '1.19'
         check-latest: true
         cache: true
     - run: GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -o wait4it
     - name: Cache wait4it
       uses: actions/cache@v3
       with:
         path: wait4it
         key: wait4it-${{ github.run_id }}
         restore_keys: wait4it-

  redis:
    runs-on: ubuntu-latest
    needs: build
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - name: Cache wait4it
        uses: actions/cache@v3
        with:
          path: wait4it
          key: wait4it-${{ github.run_id }}
      - run: ./wait4it -type=redis -p=6379 -t=60 -h=127.0.0.1